export const DEFAULT_PLANS = [
  {
    name: 'Trial',
    description: 'Free trial plan for evaluation',
    basePrice: 0,
    billingCycle: 'monthly' as const,
    isActive: true,
    isPublic: false,
    isDefault: false,
    sortOrder: 0,
    modules: ['products', 'categories', 'orders', 'payments', 'shifts', 'customers', 'reports'],
    limits: {
      maxUsers: 5,
      maxProducts: 50,
      maxCategories: 10,
      maxOutlets: 1,
      maxOrdersPerMonth: 200,
      maxInventoryItems: 100,
      maxWarehouses: 1,
    },
    addOns: [],
  },
  {
    name: 'Starter',
    description: 'Perfect for small single-outlet retail & F&B',
    basePrice: 199000,
    billingCycle: 'monthly' as const,
    isActive: true,
    isPublic: true,
    isDefault: true,
    sortOrder: 1,
    modules: ['products', 'categories', 'modifiers', 'inventory', 'warehouses', 'orders', 'payments', 'shifts', 'customers', 'reports', 'promotions'],
    limits: {
      maxUsers: 10,
      maxProducts: 200,
      maxCategories: 30,
      maxOutlets: 1,
      maxOrdersPerMonth: 1000,
      maxInventoryItems: 500,
      maxWarehouses: 1,
    },
    addOns: [
      { id: 'addon-outlet', name: 'Extra Outlet', description: 'Tambah 1 outlet tambahan', price: 75000, type: 'limit', value: 1 },
      { id: 'addon-api', name: 'API Access', description: 'Akses REST API eksternal', price: 100000, type: 'module', value: 'api-access' },
    ],
  },
  {
    name: 'Pro',
    description: 'Advanced features for growing businesses with multi-outlet',
    basePrice: 499000,
    billingCycle: 'monthly' as const,
    isActive: true,
    isPublic: true,
    isDefault: false,
    sortOrder: 2,
    modules: ['products', 'categories', 'modifiers', 'inventory', 'warehouses', 'orders', 'payments', 'shifts', 'customers', 'reports', 'promotions', 'multi-outlet', 'qr-printing', 'auto-print', 'reports-advanced', 'api-access', 'restaurant'],
    limits: {
      maxUsers: 25,
      maxProducts: 1000,
      maxCategories: 100,
      maxOutlets: 5,
      maxOrdersPerMonth: 5000,
      maxInventoryItems: 2000,
      maxWarehouses: 5,
    },
    addOns: [
      { id: 'addon-outlet', name: 'Extra Outlet', description: 'Tambah 1 outlet tambahan', price: 75000, type: 'limit', value: 1 },
    ],
  },
  {
    name: 'Enterprise',
    description: 'Unlimited capacity and full feature suite for large chains',
    basePrice: 999000,
    billingCycle: 'monthly' as const,
    isActive: true,
    isPublic: true,
    isDefault: false,
    sortOrder: 3,
    modules: ['products', 'categories', 'modifiers', 'inventory', 'warehouses', 'orders', 'payments', 'shifts', 'customers', 'reports', 'promotions', 'multi-outlet', 'hub-management', 'qr-printing', 'auto-print', 'reports-advanced', 'api-access', 'restaurant', 'hospitality'],
    limits: {
      maxUsers: -1,
      maxProducts: -1,
      maxCategories: -1,
      maxOutlets: -1,
      maxOrdersPerMonth: -1,
      maxInventoryItems: -1,
      maxWarehouses: -1,
    },
    addOns: [],
  },
];
