version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: posmono-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: posmono-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: posmono-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file: ../backend/.env
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data:
  redis_data:
